version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  deploy-to-heroku:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.10
      - run:
          name: "Build and Push to Heroku"
          command: |
            # Add steps here to build your application
            # For example, if you're using npm:
           npm install
           npm run build
            
            # Ensure you have the necessary environment variables set in CircleCI project settings:
            #HEROKU_EMAIL: 
            # HEROKU_API_KEY: 

            echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
            heroku container:login
            heroku container:push web --app react-portfolio2
            heroku container:release web --app react-portfolio2

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - deploy-to-heroku:
          requires:
            - say-hello
